# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 莫名其妙 -- 编程
email: yangning1123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The answer to life, the universe and everything is 42.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  yangning1123

# Build settings
markdown: kramdown
